GET https://expense-app-miqsuqs.onrender.com/api/expenses
###
GET https://expense-app-miqsuqs.onrender.com/api/expenses/5
###
POST https://expense-app-miqsuqs.onrender.com/api/expenses HTTP/1.1
content-type: application/json

{
  "product_name": "Vessapaperi",
  "product_amount": 8,
  "product_category": "paperi",
  "shop_name": "Alepa",
  "expense_date": "2023-01-18",
  "cost": "7.03"
}
###
PUT https://expense-app-miqsuqs.onrender.com/api/expenses HTTP/1.1
content-type: application/json

{
  "expense_id": 9,
  "product_name": "Vessapaperi",
  "product_amount": 1,
  "product_category": "Paperi",
  "shop_name": "Alepa",
  "expense_date": "2023-01-17",
  "cost": "7.03"
}
###
DELETE https://expense-app-miqsuqs.onrender.com/api/expenses/9
###
GET https://expense-app-miqsuqs.onrender.com/health
